OBJECT_BLOCK = "block"
OBJECT_SAW_BLOCK = "sawblock"
OBJECT_LIGHT = "light"
OBJECT = "object"
EXPAND_FIELD_UP = "expand up"
EXPAND_FIELD_RIGHT = "expand right"
RETRACT_FIELD_DOWN = "retract down"
RETRACT_FIELD_LEFT = "retract left"
DECODING_FAILURE = "decode failure"
NO_OBJECT_SELECTED = "no object selected"
TAG_WALL = "wall"
TAG_GROUND = "ground"
BOB_ANGLE = 60
SWINGING_LIGHT_RADIUS = 500
ROPE_WIDTH = 20
HEIGHT = 600
WIDTH = 800
FPS = 60

CONSTANTS = [WIDTH, HEIGHT, FPS]
