OBJECT_BLOCK = "block"
OBJECT_SAW_BLOCK = "sawblock"
OBJECT_LIGHT = "light"
OBJECT_SETTINGS = "settings"
OBJECT_SWINGING_LIGHT = "swinging light"
OBJECT = "object"

EXPAND_FIELD_UP = "expand up"
EXPAND_FIELD_RIGHT = "expand right"
RETRACT_FIELD_DOWN = "retract down"
RETRACT_FIELD_LEFT = "retract left"

DECODING_FAILURE = "decode failure"
NO_OBJECT_SELECTED = "no object selected"
MUSIC_IN_GAME1 = "ingame_1"
TAG_WALL = "wall"
TAG_GROUND = "ground"

BOB_ANGLE = 60
ROTATION_STEP = 40
BATARANG_IMAGE = "batarang2.png"
SAW_IMAGE = "saw.png"
SAW_DIMENSION = (50, 50)
TICKS_FOR_60_FPS = 17
DEFAULT_START_POSITION = (100, 100)
BATARANG_WIDTH = 35
BATARANG_HEIGHT = 15
SWINGING_LIGHT_RADIUS = 250
LIGHT_RADIUS = 300
SAW_ROPE_ANGLE = 45
SAW_ROPE_WIDTH = 10
ROPE_WIDTH = 20
BLOCK_SIZE = 32
HEIGHT = 600
WIDTH = 800
FPS = 60


CONSTANTS = [WIDTH, HEIGHT, FPS]
